services:
  fastapi_app:
    build: .
    environment:
      - POSTGRES_HOST=psql_db
    env_file:
      - ./.env
    container_name: fastapi_app
    ports:
      - '8000:8000'
    depends_on:
      - psql_db
    command: sh -c 'uvicorn main:app --host 0.0.0.0'
  
  psql_db:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: